# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

factorial <- function(n) {
    .Call(`_kendalltau_factorial`, n)
}

#' Kendall's tau correlation coeficient
#'
#'Computes Kendall's tau correlation coeficient through Rcpp.
#'
#' @param x numeric vector
#' @param y numeric vector
#' @return double
#' @examples
#' fasttau(c(1,2,3,4,5),c(2,1,4,3,6))
#' @export
fasttau <- function(x, y) {
    .Call(`_kendalltau_fasttau`, x, y)
}

